# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('run_freq', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('activationkey', models.CharField(blank=True, max_length=1024, null=True)),
                ('registration_hash', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Mobile2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('mobile_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foo.Employees')),
            ],
            options={
                'db_table': 'mobile2',
            },
        ),
        migrations.CreateModel(
            name='Pingresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, db_column='HostName', max_length=1024, null=True)),
                ('ip_adress_ipv6', models.CharField(blank=True, db_column='Ip_adress_IPv6', max_length=1024, null=True)),
                ('ip_adress_ipv4', models.CharField(blank=True, db_column='Ip_adress_Ipv4', max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=1024, null=True)),
                ('company_id', models.ForeignKey(blank=True, db_column='Company_id_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foo.Company')),
            ],
            options={
                'db_table': 'PingResults',
            },
        ),
        migrations.CreateModel(
            name='Runfrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foo.Company')),
            ],
            options={
                'db_table': 'Runfrequency',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=2048, null=True)),
                ('role', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('company_id_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foo.Subscriptions'),
        ),
    ]
