# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Runfrequency',
            new_name='Activity',
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
    ]
