# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0002_auto_20181227_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingresults',
            name='company_id',
        ),
        migrations.AddField(
            model_name='pingresults',
            name='activity_id',
            field=models.ForeignKey(blank=True, db_column='Company_id_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foo.Activity'),
        ),
    ]
