# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0004_adextractor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adextractor',
            table='AdExtractor',
        ),
    ]
