# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0005_auto_20181227_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adextractor',
            name='Active_Directory_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='adextractor',
            name='Logon',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adextractor',
            name='Password_Last_set',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adextractor',
            name='When_changed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adextractor',
            name='When_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
